# Set up code coverage flags
function(enable_coverage target)
    if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        message(STATUS "Enabled coverage")
        target_compile_options(${target} INTERFACE --coverage -O0 -g)
        target_link_libraries(${target} INTERFACE --coverage)
    else()
        message(WARNING "Cannot enable coverage on non-clang/g++ compiler")
    endif()
endfunction()
